(function(){
'use strict';
const KEY='onb_community_v5';
const EMOJIS=['😀','😄','😁','😂','🤣','😊','😍','🥰','😘','😎','🤔','😮','😢','😭','😡','👍','👎','👏','🙏','🔥','❤️','💯','🎉','🎓','📚','💻','🎨','🚀','⭐','💡','🙌','🤝','👀','💬','✨','🫶','😴','🤯','🥳'];
const defaults={
 user:{id:1,name:'Gia Huy',avatar:'😎',avatarImage:'',points:500,frame:'frame-neon',bg:'bg-aurora',bio:'Sinh viên · Thành viên Oxford Nhà Bè',skills:['C++','Thiết kế web','Giao tiếp'],inventory:['frame-neon'],files:[],badges:['🎓 Sinh viên','⭐ Thành viên tích cực','🏆 Người mới'],joined:'2026'},
 servers:[
  {id:'onb',name:'Oxford Nhà Bè',icon:'ONB',members:1248,privacy:'Công khai',channels:[
   {id:'general',name:'phòng-chung',topic:'Nơi sinh viên Oxford Nhà Bè giao lưu và giúp đỡ nhau.',type:'text'},
   {id:'announcements',name:'thông-báo-nhà-trường',topic:'Thông báo chính thức từ nhà trường.',type:'text',official:true},
   {id:'fresh',name:'tân-sinh-viên',topic:'Hỏi đáp dành cho sinh viên mới.',type:'text'},
   {id:'study',name:'học-tập',topic:'Chia sẻ tài liệu, bài tập và kinh nghiệm học tập.',type:'text'},
   {id:'career',name:'cơ-hội-nghề-nghiệp',topic:'Việc làm, thực tập, CV và networking.',type:'text'},
   {id:'clubs',name:'câu-lạc-bộ',topic:'Khám phá và tham gia các CLB của trường.',type:'text'},
   {id:'gaming',name:'gaming',topic:'Game, giải trí và giao lưu.',type:'text'},
   {id:'voice-study',name:'phòng-học-chung',topic:'Kênh voice cộng đồng — bản demo giao diện.',type:'voice'},
   {id:'voice-lounge',name:'voice-lounge',topic:'Trò chuyện tự do — bản demo giao diện.',type:'voice'}
  ],roles:[
   {name:'Admin',color:'#ed4245',permissions:{manageServer:true,manageMembers:true,manageChannels:true,manageRoles:true,send:true,attach:true}},
   {name:'Moderator',color:'#57f287',permissions:{manageServer:false,manageMembers:true,manageChannels:false,manageRoles:false,send:true,attach:true}},
   {name:'Giảng viên',color:'#f0b232',permissions:{manageServer:false,manageMembers:false,manageChannels:false,manageRoles:false,send:true,attach:true}},
   {name:'Sinh viên',color:'#5865f2',permissions:{manageServer:false,manageMembers:false,manageChannels:false,manageRoles:false,send:true,attach:true}}
  ]},
  {id:'clb',name:'CLB & Hoạt động',icon:'🎓',members:426,privacy:'Công khai',channels:[
   {id:'club-home',name:'sảnh-clb',topic:'Danh sách các câu lạc bộ và hoạt động.',type:'text'},
   {id:'club-it',name:'clb-công-nghệ',topic:'Lập trình, AI, web và dự án.',type:'text'},
   {id:'club-design',name:'clb-thiết-kế',topic:'Thiết kế đồ họa, UI/UX và portfolio.',type:'text'},
   {id:'club-english',name:'clb-tiếng-anh',topic:'Speaking club và giao tiếp.',type:'text'},
   {id:'club-sport',name:'clb-thể-thao',topic:'Thể thao và hoạt động ngoại khóa.',type:'text'},
   {id:'club-voice',name:'phòng-họp-clb',topic:'Voice phòng họp CLB — bản demo.',type:'voice'}
  ],roles:[
   {name:'Chủ nhiệm CLB',color:'#f0b232',permissions:{manageServer:true,manageMembers:true,manageChannels:true,manageRoles:true,send:true,attach:true}},
   {name:'Ban tổ chức',color:'#57f287',permissions:{manageServer:false,manageMembers:true,manageChannels:true,manageRoles:false,send:true,attach:true}},
   {name:'Thành viên',color:'#5865f2',permissions:{manageServer:false,manageMembers:false,manageChannels:false,manageRoles:false,send:true,attach:true}}
  ]}
 ],members:[
  {id:1,name:'Gia Huy',avatar:'😎',role:'Sinh viên',online:true,status:'Đang học',bio:'Thích lập trình và game.'},
  {id:2,name:'Minh Anh',avatar:'👩🏻‍💻',role:'Moderator',online:true,status:'Đang trực tuyến',bio:'Hỗ trợ sinh viên.'},
  {id:3,name:'An Designer',avatar:'🎨',role:'Sinh viên',online:true,status:'Đang thiết kế',bio:'UI/UX · Branding'},
  {id:4,name:'Tuấn',avatar:'🧑🏻‍💻',role:'Giảng viên',online:true,status:'Đang dạy học',bio:'Hỗ trợ học tập.'},
  {id:5,name:'Lan',avatar:'👩🏻‍🎓',role:'Sinh viên',online:false,status:'Ngoại tuyến',bio:'Ngôn ngữ Anh.'},
  {id:6,name:'Oxford Bot',avatar:'🤖',role:'Admin',online:true,status:'Hỗ trợ cộng đồng',bio:'Bot của Oxford Nhà Bè.'},
  {id:7,name:'Quốc Cường',avatar:'🧑🏻‍🎨',role:'Sinh viên',online:true,status:'Đang học',bio:'CNTT'},
  {id:8,name:'Ngọc Duy Long',avatar:'🧑🏻‍💻',role:'Sinh viên',online:true,status:'Đang online',bio:'Lập trình C++'}
 ],messages:{
  general:[
   {id:1,member:2,text:'Chào mọi người 👋 Ai mới vào trường thì giới thiệu một chút nhé!',time:'09:18',reactions:[{emoji:'👋',count:7},{emoji:'❤️',count:2}]},
   {id:2,member:3,text:'Mình đang tìm nhóm học CNTT, mọi người có nhóm nào đang hoạt động không?',time:'09:21',reactions:[{emoji:'👍',count:4},{emoji:'❤️',count:2}]},
   {id:3,member:6,text:'Bạn có thể vào #học-tập hoặc tạo nhóm riêng. Hoạt động cộng đồng cũng giúp bạn nhận ⭐ điểm ONB.',time:'09:22',reactions:[{emoji:'⭐',count:5}]}
  ],
  announcements:[
   {id:4,member:6,text:'📢 THÔNG BÁO NHÀ TRƯỜNG\nChào mừng sinh viên đến với Cộng đồng Oxford Nhà Bè. Các thông báo học vụ, sự kiện và hoạt động sẽ được đăng tại đây.',time:'08:00',reactions:[{emoji:'📢',count:12}]},
   {id:5,member:4,text:'🎓 Tuần này có hoạt động định hướng tân sinh viên. Hãy theo dõi lịch trên website trường và tham gia kênh #tân-sinh-viên.',time:'08:30',reactions:[{emoji:'🎓',count:6}]}
  ],
  fresh:[{id:6,member:2,text:'Tân sinh viên cần hỗ trợ chọn ngành có thể hỏi trực tiếp tại đây nhé. Mọi người hãy giúp nhau trả lời.',time:'10:02',reactions:[{emoji:'❤️',count:4}]}],
  study:[{id:7,member:8,text:'Mình vừa chia sẻ bộ tài liệu lập trình cơ bản. Ai cần thì phản hồi nhé!',time:'10:15',reactions:[{emoji:'📚',count:5}]}],
  career:[{id:8,member:5,text:'Có bạn nào biết chỗ thực tập thiết kế đồ họa mùa hè này không?',time:'11:07',reactions:[{emoji:'👍',count:3}]}],
  clubs:[{id:9,member:2,text:'🎉 Các CLB đang mở đăng ký thành viên mới. Vào #câu-lạc-bộ để xem thông tin.',time:'12:10',reactions:[{emoji:'🎉',count:8}]}],
  gaming:[{id:10,member:7,text:'Tối nay ai chơi game không? 😎',time:'12:30',reactions:[{emoji:'🔥',count:3}]}],
  'club-home':[{id:11,member:2,text:'🎓 Chào mừng đến khu vực CLB! Bạn có thể tìm CLB Công nghệ, Thiết kế, Tiếng Anh và Thể thao.',time:'09:00'}],
  'club-it':[{id:12,member:8,text:'CLB Công nghệ đang chuẩn bị workshop web cơ bản. Ai muốn tham gia thì comment nhé!',time:'09:45'}],
  'club-design':[{id:13,member:3,text:'Tuần này CLB Thiết kế có buổi review portfolio.',time:'10:20'}],
  'club-english':[{id:14,member:5,text:'Speaking club tối thứ sáu: chủ đề “My future career”.',time:'11:15'}],
  'club-sport':[{id:15,member:2,text:'🏃 Hoạt động thể thao cuối tuần đã mở đăng ký.',time:'11:30'}],
  'voice-study':[], 'voice-lounge':[]
 },
 selectedServer:'onb',selectedChannel:'general',selectedTab:'overview',lastDaily:'',notifications:3,voiceParticipants:{'voice-study':[2,3],'voice-lounge':[4],'club-voice':[2,4]},
 missions:[
  {id:'daily',title:'Điểm danh cộng đồng',desc:'Mỗi ngày mở Cộng đồng và nhận điểm.',reward:20,done:false},
  {id:'message',title:'Gửi tin nhắn hữu ích',desc:'Gửi một tin nhắn trong kênh cộng đồng.',reward:15,done:false},
  {id:'reaction',title:'Tương tác với bài viết',desc:'Thả reaction cho một tin nhắn.',reward:10,done:false},
  {id:'profile',title:'Hoàn thiện hồ sơ',desc:'Thêm CV, bằng cấp hoặc trang trí profile.',reward:25,done:false},
  {id:'club',title:'Khám phá CLB',desc:'Tham gia khu vực CLB & Hoạt động.',reward:15,done:false}
 ]
};
let state=load();
let pendingFileMode='chat';let pendingProfileCategory='Hồ sơ';
let replyTo=null;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x?merge(clone(defaults),x):clone(defaults)}catch(e){return clone(defaults)}}
function merge(a,b){Object.assign(a,b);a.user=Object.assign(a.user||{},b.user||{});a.servers=b.servers||a.servers;a.members=b.members||a.members;a.messages=Object.assign(a.messages||{},b.messages||{});a.missions=b.missions||a.missions;a.voiceParticipants=Object.assign(a.voiceParticipants||{},b.voiceParticipants||{});return a}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){toast('Bộ nhớ trình duyệt gần đầy. Hãy xóa bớt file hồ sơ.','warn')}}
function server(){return state.servers.find(s=>s.id===state.selectedServer)||state.servers[0]}
function channel(){return server().channels.find(c=>c.id===state.selectedChannel)||server().channels[0]}
function member(id){const m=state.members.find(m=>m.id===id)||state.members[0];if(m&&m.id===1){m.avatar=state.user.avatar;m.avatarImage=state.user.avatarImage||'';m.name=state.user.name}return m}
function escape(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initials(name){return name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function timeNow(){return new Date().toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}
function toast(text,type='success'){const d=document.createElement('div');d.className='toast '+type;d.textContent=text;$('#toastStack').appendChild(d);setTimeout(()=>d.remove(),2800)}
function init(){renderAll();bind();claimDaily();buildEmojiPicker()}
function renderAll(){renderServers();renderChannels();renderHeader();renderMessages();renderMembers();renderProfile();renderShop();updateNotification()}
function renderServers(){const box=$('#customServers');box.innerHTML='';state.servers.forEach(s=>{const b=document.createElement('button');b.className='server-icon '+(s.id===state.selectedServer?'active':'');b.textContent=s.icon||initials(s.name);b.title=s.name;b.onclick=()=>selectServer(s.id);box.appendChild(b)});$$('.server-icon.home').forEach(b=>b.classList.toggle('active',state.selectedServer==='onb'))}
function selectServer(id){state.selectedServer=id;state.selectedChannel=server().channels[0].id;save();renderAll();if(id==='clb')completeMission('club')}
function renderChannels(){const list=$('#channelList'),s=server();list.innerHTML='';const add=(title,arr,icon)=>{if(!arr.length)return;const cat=document.createElement('div');cat.className='category';cat.textContent=title;list.appendChild(cat);arr.forEach(c=>{const b=document.createElement('button');b.className='channel-item '+(c.id===state.selectedChannel?'active':'');b.dataset.channel=c.id;b.innerHTML='<span class="hash">'+(c.type==='voice'?'🔊':'#')+'</span>'+escape(c.name)+(c.official?'<span class="unread">NEW</span>':'');b.onclick=()=>{state.selectedChannel=c.id;if(c.type==='voice'){save();renderAll();openVoicePanel(c);return}state.selectedChannel=c.id;replyTo=null;save();renderAll()};list.appendChild(b)})};add('TEXT CHANNELS',s.channels.filter(c=>c.type==='text'),'#');add('VOICE / STUDY',s.channels.filter(c=>c.type==='voice'),'🔊')}
function renderHeader(){const s=server(),c=channel();$('#serverName').textContent=s.name;$('#serverMemberCount').textContent=(s.members||state.members.length).toLocaleString('vi-VN')+' thành viên';$('#currentChannel').textContent=c.name;$('#channelTopic').textContent=c.topic;$('#messageInput').placeholder='Nhắn #'+c.name;$('#channelIcon').textContent=c.type==='voice'?'🔊':'#';$('#channelBadge').textContent=c.official?'CHÍNH THỨC':c.type==='voice'?'VOICE':'';$('#topName').textContent=state.user.name;$('#sideName').textContent=state.user.name;$('#topAvatar').innerHTML=avatarMarkup(state.user);$('#sideAvatar').innerHTML=avatarMarkup(state.user);applyAvatar($('#sideAvatar'));applyAvatar($('#topAvatar'));$('#noticeTitle').textContent=c.official?'📢 Thông báo nhà trường':c.type==='voice'?'🔊 Kênh thoại cộng đồng':'💡 Cộng đồng học tập';$('#noticeText').textContent=c.official?'Chỉ đăng thông báo chính thức, lịch học, sự kiện và hoạt động của trường.':c.type==='voice'?'Đây là mô phỏng voice channel. Kết nối WebRTC để dùng voice thật.':'Chia sẻ văn minh, tôn trọng thành viên và cùng nhau nhận điểm ONB.'}
function avatarMarkup(u, cls=''){const src=u&&u.avatarImage;const content=src?'<img src="'+src+'" alt="avatar">':escape(u&&u.avatar||'🙂');return '<span class="avatar-content '+cls+'">'+content+'</span>'}
function applyAvatar(el){if(!el)return;el.style.boxShadow='';el.style.border='';if(state.user.frame==='frame-neon'){el.style.boxShadow='0 0 9px #00e5ff';el.style.border='2px solid #00e5ff'}else if(state.user.frame==='frame-gold'){el.style.boxShadow='0 0 9px #f0b232';el.style.border='2px solid #f0b232'}else if(state.user.frame==='frame-rose'){el.style.boxShadow='0 0 9px #ff6b9a';el.style.border='2px solid #ff6b9a'}}
function renderMessages(){
 const box=$('#messages'); box.innerHTML=''; const c=channel(), arr=state.messages[state.selectedChannel]||[];
 if(!arr.length){box.innerHTML='<div class="welcome"><div class="welcome-icon">'+(c.type==='voice'?'🔊':'#')+'</div><h2>Chào mừng đến #'+escape(c.name)+'!</h2><p>'+escape(c.topic)+'<br>Hãy bắt đầu cuộc trò chuyện. Bạn có thể gửi tin nhắn, ảnh, file, reaction và trả lời từng tin.</p></div>';return}
 arr.forEach(m=>{
  const u=member(m.member), el=document.createElement('article'); el.className='message';
  const reactions=(m.reactions||[]).map(r=>`<button class="reaction ${r.users&&r.users.includes(1)?'mine':''}" data-react="${m.id}" data-emoji="${escape(r.emoji)}">${escape(r.emoji)} ${r.count}</button>`).join('');
  let media='';
  if(m.file){
   if(m.file.kind==='image') media=`<img class="message-image" src="${m.file.data}" alt="${escape(m.file.name)}" data-open-image="${m.id}">`;
   else media=`<div class="file-card"><span class="file-icon">📎</span><div><b>${escape(m.file.name)}</b><small>${formatBytes(m.file.size)} · ${escape(m.file.type||'Tệp')}</small></div><button class="reaction" data-download="${m.id}">Tải</button></div>`;
  }
  const reply=m.reply?`<div class="reply-line">↩ Trả lời ${escape(member(m.reply.member).name)}: ${escape((m.reply.text||'').slice(0,80))}</div>`:'';
  const own=m.member===1?`<button data-edit="${m.id}">✎</button><button data-delete="${m.id}">🗑</button>`:'';
  el.innerHTML=`<div class="message-avatar">${avatarMarkup(u)}<span class="status-dot"></span></div><div class="message-body"><div class="message-meta"><b>${escape(u.name)}</b><span class="role-pill">${escape(u.role)}</span><span class="message-time">${escape(m.time||'vừa xong')}${m.edited?' · đã sửa':''}</span></div><div class="message-text">${escape(m.text||'')}</div>${media}${reply}<div class="reactions">${reactions}<button class="reaction add-react" data-react-add="${m.id}">＋</button></div></div><div class="message-toolbar"><button data-reply="${m.id}" title="Trả lời">↩</button><button data-react-add="${m.id}" title="Reaction">☺</button>${own}<button data-pin="${m.id}">📌</button></div>`;
  box.appendChild(el);
 });
 box.scrollTop=box.scrollHeight;
}
function renderMembers(){const box=$('#memberList');box.innerHTML='';const online=state.members.filter(m=>m.online);$('#onlineCount').textContent=online.length;$('#memberTotal').textContent=state.members.length;const c=channel();if(c&&c.type==='voice'){const ids=state.voiceParticipants?.[c.id]||[];const wrap=document.createElement('div');wrap.className='voice-members-section';wrap.innerHTML='<div class="voice-members-title">🔊 ĐANG THAM GIA — '+ids.length+'</div>';if(ids.length){ids.map(id=>member(id)).forEach(m=>{const r=document.createElement('div');r.className='member-row voice-participant';r.dataset.memberName=m.name.toLowerCase();r.innerHTML='<div class="member-avatar voice-avatar">'+avatarMarkup(m)+'</div><div class="member-info"><b>'+escape(m.name)+'</b><small><span class="voice-state-dot"></span>Đang trong phòng · Mic bật</small></div>';r.onclick=()=>openMemberCard(m);wrap.appendChild(r)})}else{wrap.innerHTML+='<div class="empty-state voice-empty">Chưa có ai trong phòng thoại.<br>Hãy nhấn “Tham gia” để bắt đầu.</div>'}box.appendChild(wrap)}const title=document.createElement('div');title.className='member-subtitle';title.textContent='TRỰC TUYẾN — '+online.length;box.appendChild(title);online.forEach(m=>{const r=document.createElement('div');r.className='member-row';r.dataset.memberName=m.name.toLowerCase();r.innerHTML='<div class="member-avatar">'+avatarMarkup(m)+'</div><div class="member-info"><b>'+escape(m.name)+'</b><small><span class="role-dot" style="background:'+roleColor(m.role)+'"></span>'+escape(m.role)+' · '+escape(m.status||'Online')+'</small></div>';r.onclick=()=>openMemberCard(m);box.appendChild(r)})}
function roleColor(role){for(const s of state.servers){const r=s.roles.find(x=>x.name===role);if(r)return r.color}return '#5865f2'}
function renderProfile(){const u=state.user;$('#profileTitle').textContent=u.name;$('#profileAvatar').innerHTML=avatarMarkup(u);$('#pointsValue').textContent=u.points;$('#profileCover').className='profile-cover '+u.bg;$('#profileAvatar').className='profile-avatar '+u.frame;$('#profileBio').textContent=u.bio||'Sinh viên · Thành viên Oxford Nhà Bè';$('#messageStat').textContent=Object.values(state.messages).flat().filter(m=>m.member===1).length;$('#badgeStat').textContent=(u.badges||[]).length;renderOverview();renderFiles();renderCustomize();renderMissions()}
function renderOverview(){$('#overviewTab').innerHTML='<div class="profile-section"><h4>Giới thiệu</h4><div class="bio-box">'+escape(state.user.bio||'Chưa có giới thiệu.')+'</div></div><div class="profile-section"><h4>Kỹ năng</h4><div class="skill-list">'+(state.user.skills||[]).map(x=>'<span class="skill">'+escape(x)+'</span>').join('')+'</div></div><div class="profile-section"><h4>Huy hiệu</h4><div class="skill-list">'+(state.user.badges||[]).map(x=>'<span class="skill">'+escape(x)+'</span>').join('')+'</div></div><div class="profile-section"><h4>Thành viên từ</h4><div class="bio-box">'+escape(state.user.joined||'2026')+' · Oxford Nhà Bè</div></div>'}
function renderFiles(){const files=state.user.files||[];const cv=files.filter(f=>f.category==='CV');const cert=files.filter(f=>f.category==='Bằng cấp / chứng chỉ');const other=files.filter(f=>!['CV','Bằng cấp / chứng chỉ'].includes(f.category));const item=f=>'<div class="document-item"><div class="document-icon">'+(f.kind==='image'?'🖼️':f.type==='application/pdf'?'📕':'📄')+'</div><div><b>'+escape(f.name)+'</b><small>'+formatBytes(f.size)+' · '+escape(f.category||'Hồ sơ')+'</small></div><div class="doc-actions"><button data-doc-open="'+files.indexOf(f)+'">Xem</button><button data-doc-download="'+files.indexOf(f)+'">Tải</button><button data-doc-delete="'+files.indexOf(f)+'">Xóa</button></div></div>';const group=(title,arr)=>'<div class="profile-section"><h4>'+title+' <span class="file-count">'+arr.length+'</span></h4>'+(arr.length?arr.map(item).join(''):'<div class="empty-state compact">Chưa có tài liệu.</div>')+'</div>';$('#filesTab').innerHTML='<div class="upload-box"><b>📁 Hồ sơ học tập & nghề nghiệp</b><p class="muted">Tải CV, bằng cấp, bảng điểm, chứng chỉ hoặc portfolio từ máy tính/điện thoại. Tài liệu sẽ hiển thị ngay trong profile.</p><div class="upload-actions"><button id="uploadCV">＋ Tải CV</button><button id="uploadCertificate">＋ Tải bằng cấp / chứng chỉ</button><button id="uploadOther">＋ Tài liệu khác</button></div></div>'+group('📄 CV & Resume',cv)+group('🎓 Bằng cấp & Chứng chỉ',cert)+group('📦 Portfolio & Tài liệu khác',other)}
function renderCustomize(){const owned=new Set(state.user.inventory||[]);$('#customizeTab').innerHTML='<div class="custom-section"><h4>Avatar</h4><div class="avatar-upload-box"><div class="large-avatar-preview">'+avatarMarkup(state.user)+'</div><div><b>Ảnh đại diện</b><p class="muted">Chọn ảnh JPG, PNG hoặc WEBP từ thiết bị.</p><button id="uploadAvatar" class="primary-btn">📷 Tải ảnh từ thiết bị</button><button id="removeAvatar" class="primary-btn" style="background:#404249;margin-left:5px">Xóa ảnh</button></div></div><div class="option-row">'+['😎','🧑🏻‍💻','👩🏻‍🎓','🎨','🚀','🐱','🦊','🤖','🧑🏻‍🏫','🧑🏻‍🚀'].map(a=>'<button class="option '+(state.user.avatar===a?'selected':'')+'" data-avatar="'+a+'">'+a+'</button>').join('')+'</div></div><div class="custom-section"><h4>Khung avatar</h4><div class="option-row">'+[['frame-none','Mặc định'],['frame-neon','Neon'],['frame-gold','Gold'],['frame-rose','Rose']].map(([id,n])=>'<button class="option '+(state.user.frame===id?'selected':'')+(id!=='frame-none'&&!owned.has(id)?' locked':'')+'" data-frame="'+id+'"><span class="frame-demo '+id+'">'+state.user.avatar+'</span><br><small>'+n+(id!=='frame-none'&&!owned.has(id)?' · Chưa mua':'')+'</small></button>').join('')+'</div></div><div class="custom-section"><h4>Nền hồ sơ</h4><div class="option-row">'+[['bg-aurora','Aurora'],['bg-sunset','Sunset'],['bg-night','Night'],['bg-mint','Mint']].map(([id,n])=>'<button class="option '+(state.user.bg===id?'selected':'')+(id!=='bg-aurora'&&!owned.has(id)?' locked':'')+'" data-bg="'+id+'"><span class="frame-demo '+id+'"></span><br><small>'+n+(id!=='bg-aurora'&&!owned.has(id)?' · Chưa mua':'')+'</small></button>').join('')+'</div></div>'}
function renderMissions(){$('#missionsTab').innerHTML='<div class="custom-section"><h4>Nhiệm vụ nhận điểm</h4></div>'+state.missions.map(m=>'<div class="mission"><div><b>'+escape(m.title)+'</b><small>'+escape(m.desc)+' · +'+m.reward+' điểm</small></div><button data-mission="'+m.id+'" '+(m.done?'disabled':'')+'>'+(m.done?'Đã nhận':'Nhận điểm')+'</button></div>').join('')}
function renderShop(){const items=[{id:'frame-neon',name:'Khung Neon',desc:'Khung phát sáng nổi bật.',price:120,type:'frame',preview:'😎',cls:'frame-neon'},{id:'frame-gold',name:'Khung Gold',desc:'Phong cách thành tích.',price:180,type:'frame',preview:'👑',cls:'frame-gold'},{id:'frame-rose',name:'Khung Rose',desc:'Màu hồng dành cho profile.',price:150,type:'frame',preview:'🌸',cls:'frame-rose'},{id:'bg-sunset',name:'Nền Sunset',desc:'Nền hồ sơ cam hồng.',price:100,type:'bg',preview:'🌅',cls:'bg-sunset'},{id:'bg-night',name:'Nền Night',desc:'Nền tối hiện đại.',price:130,type:'bg',preview:'🌌',cls:'bg-night'},{id:'bg-mint',name:'Nền Mint',desc:'Nền xanh năng lượng.',price:140,type:'bg',preview:'🍃',cls:'bg-mint'},{id:'badge-star',name:'Huy hiệu Ngôi sao',desc:'Thêm huy hiệu vào profile.',price:220,type:'badge',preview:'⭐',cls:'bg-night'}];const owned=new Set(state.user.inventory||[]);$('#shopPoints').textContent=state.user.points;$('#shopGrid').innerHTML=items.map(i=>'<div class="shop-item"><div class="shop-preview '+i.cls+'">'+i.preview+'</div><h4>'+i.name+'</h4><p>'+i.desc+'</p><span class="price">⭐ '+i.price+'</span><button class="buy-btn" data-buy="'+i.id+'" '+(owned.has(i.id)?'disabled':'')+'>'+(owned.has(i.id)?'Đã sở hữu':'Mua vật phẩm')+'</button></div>').join('')}
function updateNotification(){$('#notificationDot').style.display=state.notifications?'block':'none'}
function openModal(id){$(id).classList.add('open')}function closeModal(el){el.closest('.modal').classList.remove('open')}
function bind(){
 document.addEventListener('click',e=>{if(e.target.classList.contains('modal-close'))closeModal(e.target);if(e.target.classList.contains('modal'))e.target.classList.remove('open')});
 $('#openProfile').onclick=()=>openModal('#profileModal');$('#openProfile2').onclick=()=>openModal('#profileModal');$('#openShop').onclick=()=>openModal('#shopModal');$('#mobileShop').onclick=()=>openModal('#shopModal');
 $('#openMembers').onclick=()=>$('#memberSidebar').style.display='block';$('#closeMembers').onclick=()=>$('#memberSidebar').style.display='none';$('#addMember').onclick=addMemberModal;
 $('#createServer').onclick=createServerModal;$('#serverMenu').onclick=serverSettingsModal;$('#attachBtn').onclick=()=>{pendingFileMode='chat';$('#fileInput').value='';$('#fileInput').click()};$('#fileInput').onchange=e=>handleFile(e.target.files[0]);
 $('#emojiBtn').onclick=e=>{e.stopPropagation();$('#emojiPop').classList.toggle('open');positionEmoji()};$('#gifBtn').onclick=()=>{$('#messageInput').value+=' 🎉 ';$('#messageInput').focus()};document.addEventListener('click',e=>{if(!e.target.closest('#emojiPop')&&!e.target.closest('#emojiBtn'))$('#emojiPop').classList.remove('open')});
 $('#messageForm').onsubmit=sendMessage;$('#channelSearch').oninput=e=>filterChannels(e.target.value);$('#memberSearch').oninput=e=>filterMembers(e.target.value);
 $('#globalSearch').onclick=globalSearchModal;$('#openSearch').onclick=globalSearchModal;$('#openPins').onclick=openPins;$('#openThreads').onclick=openThreads;$('#notifications').onclick=showNotifications;$('#dismissNotice').onclick=()=>$('.notice').style.display='none';$('#schoolHub').onclick=schoolHubModal;$('#openFriends').onclick=friendsModal;$('#userSettings').onclick=settingsModal;$('#editProfile').onclick=editProfileModal;
 $$('.profile-tabs button').forEach(b=>b.onclick=()=>{state.selectedTab=b.dataset.tab;$$('.profile-tabs button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');['overview','files','customize','missions'].forEach(t=>$('#'+t+'Tab').classList.toggle('hidden',state.selectedTab!==t))});
 document.addEventListener('click',handleDynamic);
 window.addEventListener('resize',positionEmoji);
}
function handleDynamic(e){const t=e.target;if(t.dataset.avatar){state.user.avatar=t.dataset.avatar;save();renderProfile();renderHeader()}if(t.dataset.frame){const id=t.dataset.frame;if(id!=='frame-none'&&!state.user.inventory.includes(id)){toast('Bạn chưa sở hữu khung này. Vào ONB Store để mua.','warn');return}state.user.frame=id;save();renderProfile();renderHeader()}if(t.dataset.bg){const id=t.dataset.bg;if(id!=='bg-aurora'&&!state.user.inventory.includes(id)){toast('Bạn chưa sở hữu nền này. Vào ONB Store để mua.','warn');return}state.user.bg=id;save();renderProfile()}if(t.dataset.buy)buy(t.dataset.buy);if(t.dataset.mission)claimMission(t.dataset.mission);if(t.dataset.react){toggleReaction(t.dataset.react,t.dataset.emoji)}if(t.dataset.reactAdd)addReactionPicker(t.dataset.reactAdd);if(t.dataset.reply)replyMessage(t.dataset.reply);if(t.dataset.edit)editMessage(t.dataset.edit);if(t.dataset.delete)deleteMessage(t.dataset.delete);if(t.dataset.pin)pinMessage(t.dataset.pin);if(t.dataset.download)downloadMessage(t.dataset.download);if(t.dataset.openImage)openImageMessage(t.dataset.openImage);if(t.dataset.docOpen)openDocument(Number(t.dataset.docOpen));if(t.dataset.docDelete)deleteDocument(Number(t.dataset.docDelete));if(t.id==='uploadProfileFile'){pendingFileMode='profile';pendingProfileCategory='Hồ sơ';$('#fileInput').value='';$('#fileInput').click()}if(t.id==='uploadCV'){pendingFileMode='profile';pendingProfileCategory='CV';$('#fileInput').value='';$('#fileInput').click()}if(t.id==='uploadCertificate'){pendingFileMode='profile';pendingProfileCategory='Bằng cấp / chứng chỉ';$('#fileInput').value='';$('#fileInput').click()}if(t.id==='uploadOther'){pendingFileMode='profile';pendingProfileCategory='Hồ sơ';$('#fileInput').value='';$('#fileInput').click()}if(t.id==='uploadAvatar'){pendingFileMode='avatar';$('#fileInput').accept='image/*';$('#fileInput').value='';$('#fileInput').click()}if(t.id==='removeAvatar'){state.user.avatarImage='';save();renderAll();toast('Đã xóa ảnh đại diện.')}if(t.dataset.docDownload){const f=state.user.files[Number(t.dataset.docDownload)];if(f)downloadData(f.data,f.name)}if(t.dataset.emojiPick){$('#messageInput').value+=t.dataset.emojiPick;$('#messageInput').focus();$('#emojiPop').classList.remove('open')}}
function sendMessage(e){e.preventDefault();const input=$('#messageInput'),text=input.value.trim();if(!text&&!pendingChatFile)return;state.messages[state.selectedChannel]=state.messages[state.selectedChannel]||[];const m={id:Date.now(),member:1,text,time:timeNow(),reactions:[]};if(replyTo)m.reply={member:replyTo.member,text:replyTo.text};if(pendingChatFile){m.file=pendingChatFile;pendingChatFile=null}state.messages[state.selectedChannel].push(m);replyTo=null;input.value='';save();renderAll();completeMission('message');botReply(text)}
let pendingChatFile=null;
function botReply(text){if(!text||state.selectedChannel==='announcements')return;if(/cv|việc làm|thực tập/i.test(text)){setTimeout(()=>addBotMessage('Bạn có thể tải CV vào Profile → CV & bằng cấp và chia sẻ portfolio trong #cơ-hội-nghề-nghiệp. 📄'),700)}else if(/chào|hello|hi/i.test(text)){setTimeout(()=>addBotMessage('Chào bạn 👋 Chúc bạn có một ngày học tập thật tốt tại Oxford Nhà Bè!'),700)}}
function addBotMessage(text){const key=state.selectedChannel;state.messages[key]=state.messages[key]||[];state.messages[key].push({id:Date.now(),member:6,text,time:timeNow(),reactions:[{emoji:'🤖',count:1}]});save();renderMessages()}
function handleFile(file){if(!file)return;if(file.size>5*1024*1024){toast('File tối đa 5MB trong bản local demo.','warn');return}const reader=new FileReader();reader.onload=()=>{const data=reader.result;const obj={name:file.name,size:file.size,type:file.type,kind:file.type.startsWith('image/')?'image':'file',data};if(pendingFileMode==='avatar'){if(!file.type.startsWith('image/')){toast('Avatar phải là file ảnh.','warn');return}state.user.avatarImage=data;save();renderAll();toast('📷 Đã cập nhật ảnh đại diện.');pendingFileMode='chat';$('#fileInput').accept='image/*,.pdf,.doc,.docx,.ppt,.pptx,.txt';return}if(pendingFileMode==='profile'){const category=pendingProfileCategory||(/cv|resume/i.test(file.name)?'CV':/chứng|certificate|bằng/i.test(file.name)?'Bằng cấp / chứng chỉ':'Hồ sơ');state.user.files=state.user.files||[];state.user.files.push({...obj,category});save();completeMission('profile');renderProfile();openModal('#profileModal');state.selectedTab='files';syncProfileTabs();toast('Đã thêm tài liệu vào hồ sơ.')}else{pendingChatFile=obj;$('#messageInput').value='Đã đính kèm: '+file.name;toast('Đã đính kèm file. Nhấn Gửi để đăng vào kênh.')}};reader.readAsDataURL(file)}
function syncProfileTabs(){$$('.profile-tabs button').forEach(b=>b.classList.toggle('selected',b.dataset.tab===state.selectedTab));['overview','files','customize','missions'].forEach(t=>$('#'+t+'Tab').classList.toggle('hidden',state.selectedTab!==t))}
function toggleReaction(id,emoji){const m=findMessage(id);if(!m)return;m.reactions=m.reactions||[];let r=m.reactions.find(x=>x.emoji===emoji);if(!r){r={emoji,count:0,users:[]};m.reactions.push(r)}r.users=r.users||[];if(r.users.includes(1)){r.users=r.users.filter(x=>x!==1);r.count=Math.max(0,r.count-1)}else{r.users.push(1);r.count++}m.reactions=m.reactions.filter(x=>x.count>0);save();renderMessages();if(!state.missions.find(x=>x.id==='reaction')?.done)completeMission('reaction')}
function addReactionPicker(id){const m=findMessage(id);if(!m)return;openAction('<h2>☺ Thêm cảm xúc</h2><div class="option-row" id="reactionOptions">'+EMOJIS.map(x=>'<button class="option" data-pick-react="'+x+'">'+x+'</button>').join('')+'</div>');$('#reactionOptions').addEventListener('click',e=>{if(e.target.dataset.pickReact){toggleReaction(id,e.target.dataset.pickReact);closeAction()}})}
function findMessage(id){return (state.messages[state.selectedChannel]||[]).find(m=>String(m.id)===String(id))}
function addReaction(id){addReactionPicker(id)}
function replyMessage(id){const m=findMessage(id);if(!m)return;replyTo=m;$('#messageInput').placeholder='Trả lời '+member(m.member).name+'…';$('#messageInput').focus();toast('Đang trả lời tin nhắn. Nhấn Esc để hủy.');}
function editMessage(id){const m=findMessage(id);if(!m||m.member!==1)return;openAction('<h2>✎ Chỉnh sửa tin nhắn</h2><form class="form-grid" id="editMsgForm"><textarea id="editText" rows="5" required>'+escape(m.text)+'</textarea><button>Lưu thay đổi</button></form>');$('#editMsgForm').onsubmit=e=>{e.preventDefault();m.text=$('#editText').value.trim();m.edited=true;save();closeAction();renderMessages();toast('Đã chỉnh sửa tin nhắn.')}}
function deleteMessage(id){const m=findMessage(id);if(!m||m.member!==1)return;if(confirm('Xóa tin nhắn này?')){state.messages[state.selectedChannel]=state.messages[state.selectedChannel].filter(x=>String(x.id)!==String(id));save();renderMessages();toast('Đã xóa tin nhắn.')}}
function pinMessage(id){const m=findMessage(id);if(!m)return;state.pins=state.pins||{};state.pins[state.selectedChannel]=state.pins[state.selectedChannel]||[];if(!state.pins[state.selectedChannel].some(x=>String(x.id)===String(id)))state.pins[state.selectedChannel].push(m);save();toast('📌 Đã ghim tin nhắn.')}
function openPins(){const pins=(state.pins&&state.pins[state.selectedChannel])||[];openAction('<h2>📌 Tin nhắn đã ghim</h2>'+(pins.length?pins.map(m=>'<div class="search-result"><b>'+escape(member(m.member).name)+'</b><p>'+escape(m.text||'')+'</p><small>'+escape(m.time||'')+'</small></div>').join(''):'<div class="empty-state">Chưa có tin nhắn nào được ghim.</div>'))}
function openThreads(){const arr=(state.messages[state.selectedChannel]||[]).filter(m=>m.replies&&m.replies.length);openAction('<h2>💬 Threads</h2>'+(arr.length?arr.map(m=>'<div class="search-result"><b>'+escape(member(m.member).name)+'</b><p>'+escape(m.text)+'</p><small>'+m.replies.length+' phản hồi</small></div>').join(''):'<div class="empty-state">Chưa có thread. Hãy dùng ↩ trên một tin nhắn để bắt đầu trả lời.</div>'))}
function openImageMessage(id){const m=findMessage(id);if(!m||!m.file)return;openAction('<h2>🖼️ '+escape(m.file.name)+'</h2><img src="'+m.file.data+'" style="display:block;max-width:100%;max-height:65vh;margin:auto;border-radius:8px"><button id="downloadOpenImage" class="primary-btn" style="width:100%;margin-top:10px">Tải ảnh xuống</button>');$('#downloadOpenImage').onclick=()=>downloadData(m.file.data,m.file.name)}
function downloadMessage(id){const m=findMessage(id);if(!m||!m.file)return;downloadData(m.file.data,m.file.name)}
function openDocument(i){const f=(state.user.files||[])[i];if(!f)return;const isImage=f.kind==='image';const isPdf=f.type==='application/pdf';const body=isImage?'<img src="'+f.data+'" alt="'+escape(f.name)+'" style="display:block;max-width:100%;max-height:65vh;margin:auto;border-radius:8px">':isPdf?'<iframe src="'+f.data+'" title="'+escape(f.name)+'" style="width:100%;height:65vh;border:0;border-radius:8px;background:#fff"></iframe>':'<div class="empty-state">Đây là tài liệu '+escape(f.type||'file')+'. Bạn có thể tải file về thiết bị để mở bằng ứng dụng phù hợp.</div>';openAction('<h2>📄 '+escape(f.name)+'</h2>'+body+'<button id="downloadProfileDoc" class="primary-btn" style="width:100%;margin-top:10px">⬇ Tải xuống</button>');$('#downloadProfileDoc').onclick=()=>downloadData(f.data,f.name)}
function deleteDocument(i){if(confirm('Xóa tài liệu khỏi profile?')){state.user.files.splice(i,1);save();renderProfile();toast('Đã xóa tài liệu.')}}
function downloadData(data,name){const a=document.createElement('a');a.href=data;a.download=name;a.target='_blank';document.body.appendChild(a);a.click();a.remove()}
function formatBytes(n){if(!n)return '0 B';const u=['B','KB','MB','GB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3);return (n/Math.pow(1024,i)).toFixed(i?1:0)+' '+u[i]}
function buy(id){const prices={'frame-neon':120,'frame-gold':180,'frame-rose':150,'bg-sunset':100,'bg-night':130,'bg-mint':140,'badge-star':220};if((state.user.inventory||[]).includes(id))return;if(state.user.points<prices[id]){toast('Bạn chưa đủ điểm ONB. Hãy hoàn thành nhiệm vụ cộng đồng.','warn');return}state.user.points-=prices[id];state.user.inventory.push(id);if(id==='badge-star'){state.user.badges.push('⭐ Người sưu tầm')}const m=state.missions.find(x=>x.id==='profile');if(m&&!m.done){m.done=true;state.user.points+=m.reward}save();renderAll();toast('🛍️ Mua thành công! Hãy vào Profile để trang bị.')}
function completeMission(id){const m=state.missions.find(x=>x.id===id);if(!m||m.done)return;m.done=true;state.user.points+=m.reward;save();toast('⭐ +'+m.reward+' điểm ONB — '+m.title)}function claimMission(id){completeMission(id);renderAll()}
function claimDaily(){const day=new Date().toISOString().slice(0,10);if(state.lastDaily!==day){state.lastDaily=day;completeMission('daily');save()}}
function filterChannels(q){$$('.channel-item').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q.toLowerCase())?'flex':'none')}
function filterMembers(q){$$('.member-row').forEach(r=>r.style.display=r.dataset.memberName.includes(q.toLowerCase())?'flex':'none')}
function addMemberModal(){openAction('<h2>＋ Mời thành viên</h2><p class="muted">Thêm thành viên vào cộng đồng local demo.</p><form class="form-grid" id="inviteForm"><label>Tên thành viên<input id="inviteName" required placeholder="Nguyễn Văn A"></label><label>Avatar<input id="inviteAvatar" maxlength="4" value="🙂"></label><label>Vai trò<select id="inviteRole">'+server().roles.map(r=>'<option>'+escape(r.name)+'</option>').join('')+'</select></label><button>Thêm thành viên</button></form>');$('#inviteForm').onsubmit=e=>{e.preventDefault();const name=$('#inviteName').value.trim();if(!name)return;state.members.push({id:Date.now(),name,avatar:$('#inviteAvatar').value||'🙂',role:$('#inviteRole').value,online:true,status:'Mới tham gia',bio:'Thành viên cộng đồng.'});server().members=(server().members||0)+1;save();closeAction();renderAll();toast('👥 Đã thêm '+name+' vào cộng đồng.')}}
function createServerModal(){openAction('<h2>＋ Tạo cộng đồng</h2><p class="muted">Tạo server cho lớp, CLB, nhóm dự án hoặc bạn bè.</p><form class="form-grid" id="serverForm"><label>Tên cộng đồng<input id="newServerName" required placeholder="CLB Lập trình ONB"></label><label>Biểu tượng<input id="newServerIcon" maxlength="4" value="💻"></label><label>Quyền riêng tư<select id="newServerPrivacy"><option>Công khai</option><option>Riêng tư</option></select></label><button>Tạo cộng đồng</button></form>');$('#serverForm').onsubmit=e=>{e.preventDefault();const id='s'+Date.now(),s={id,name:$('#newServerName').value.trim(),icon:$('#newServerIcon').value||'💬',members:1,privacy:$('#newServerPrivacy').value,channels:[{id:'welcome'+Date.now(),name:'phòng-chung',topic:'Kênh chung của cộng đồng mới.',type:'text'},{id:'voice'+Date.now(),name:'phòng-voice',topic:'Voice channel demo.',type:'voice'}],roles:[{name:'Chủ server',color:'#f0b232',permissions:{manageServer:true,manageMembers:true,manageChannels:true,manageRoles:true,send:true,attach:true}},{name:'Thành viên',color:'#5865f2',permissions:{manageServer:false,manageMembers:false,manageChannels:false,manageRoles:false,send:true,attach:true}}]};state.servers.push(s);state.selectedServer=id;state.selectedChannel=s.channels[0].id;state.messages[state.selectedChannel]=[];save();closeAction();renderAll();toast('🎉 Đã tạo cộng đồng '+s.name)}}
function serverSettingsModal(){const s=server();openAction('<h2>⚙ Quản lý '+escape(s.name)+'</h2><p class="muted">Role, quyền hạn và cấu hình cộng đồng.</p><div>'+s.roles.map((r,i)=>'<div class="permission-row"><b style="color:'+r.color+'">● '+escape(r.name)+'</b><label><input type="checkbox" data-perm="'+i+'" data-key="manageServer" '+(r.permissions.manageServer?'checked':'')+'> Server</label><label><input type="checkbox" data-perm="'+i+'" data-key="manageMembers" '+(r.permissions.manageMembers?'checked':'')+'> Thành viên</label><label><input type="checkbox" data-perm="'+i+'" data-key="manageChannels" '+(r.permissions.manageChannels?'checked':'')+'> Kênh</label><label><input type="checkbox" data-perm="'+i+'" data-key="manageRoles" '+(r.permissions.manageRoles?'checked':'')+'> Role</label><label><input type="checkbox" data-perm="'+i+'" data-key="attach" '+(r.permissions.attach?'checked':'')+'> Upload</label></div>').join('')+'</div><button id="savePerm" class="primary-btn" style="width:100%;margin-top:10px">Lưu quyền</button><button id="newChannel" class="primary-btn" style="width:100%;margin-top:6px;background:#404249">＋ Tạo kênh</button>');$$('[data-perm]').forEach(x=>x.onchange=()=>{s.roles[Number(x.dataset.perm)].permissions[x.dataset.key]=x.checked});$('#savePerm').onclick=()=>{save();closeAction();toast('✅ Đã lưu quyền.')};$('#newChannel').onclick=()=>{closeAction();createChannelModal()}}
function createChannelModal(){openAction('<h2>＋ Tạo kênh</h2><form class="form-grid" id="channelForm"><label>Tên kênh<input id="newChannelName" required placeholder="du-an-web"></label><label>Loại<select id="newChannelType"><option value="text">Text</option><option value="voice">Voice</option></select></label><label>Mô tả<textarea id="newChannelTopic" rows="3" placeholder="Kênh dành cho..."></textarea></label><button>Tạo kênh</button></form>');$('#channelForm').onsubmit=e=>{e.preventDefault();const c={id:'c'+Date.now(),name:$('#newChannelName').value.trim().replace(/\s+/g,'-').toLowerCase(),topic:$('#newChannelTopic').value||'Kênh cộng đồng mới.',type:$('#newChannelType').value};server().channels.push(c);state.messages[c.id]=[];save();closeAction();renderAll();toast('✅ Đã tạo #'+c.name)}}
function openMemberCard(m){
 const roleOptions=server().roles.map(r=>'<option '+(r.name===m.role?'selected':'')+'>'+escape(r.name)+'</option>').join('');
 openAction('<h2>'+escape(m.avatar)+' '+escape(m.name)+'</h2><p class="muted">'+escape(m.bio||'Thành viên cộng đồng.')+'</p><div class="permission-row"><span>Vai trò hiện tại</span><b style="color:'+roleColor(m.role)+'">● '+escape(m.role)+'</b></div><div class="permission-row"><span>Trạng thái</span><b style="color:'+(m.online?'#23a559':'#949ba4')+'">● '+(m.online?'Online':'Offline')+'</b></div><div class="permission-row"><span>Hoạt động</span><span>'+escape(m.status||'')+'</span></div><form class="form-grid" id="roleForm"><label>Đổi role<select id="memberRole">'+roleOptions+'</select></label><button>Lưu role</button></form>');
 $('#roleForm').onsubmit=e=>{e.preventDefault();m.role=$('#memberRole').value;save();closeAction();renderMembers();toast('🛡️ Đã cập nhật role cho '+m.name)}
}
function openVoicePanel(c){const ids=state.voiceParticipants?.[c.id]||[];const participants=ids.map(id=>member(id)).filter(Boolean);openAction('<h2>🔊 '+escape(c.name)+'</h2><p class="muted">'+escape(c.topic)+'</p><div class="voice-panel"><div class="voice-panel-head"><b>Đang tham gia — '+participants.length+'</b><span>🎙️ Voice</span></div><div id="voiceParticipantList">'+(participants.length?participants.map(m=>'<div class="voice-participant-card"><div class="member-avatar voice-avatar">'+avatarMarkup(m)+'</div><div><b>'+escape(m.name)+'</b><small>🟢 Đang nói · Mic bật</small></div><button class="voice-icon">🎤</button></div>').join(''):'<div class="empty-state">Chưa có thành viên trong phòng.</div>')+'</div></div><div class="voice-controls"><button id="joinVoice" class="primary-btn">🎙️ '+(ids.includes(1)?'Rời phòng':'Tham gia')+'</button><button id="muteVoice" class="primary-btn secondary">🎤 Tắt mic</button><button id="deafenVoice" class="primary-btn secondary">🎧 Điếc</button></div><p class="muted">Khi bạn tham gia, tên và trạng thái sẽ xuất hiện ngay ở cột Thành viên giống Discord.</p>');$('#joinVoice').onclick=()=>{state.voiceParticipants=state.voiceParticipants||{};state.voiceParticipants[c.id]=state.voiceParticipants[c.id]||[];const arr=state.voiceParticipants[c.id];if(arr.includes(1)){state.voiceParticipants[c.id]=arr.filter(x=>x!==1);toast('Bạn đã rời '+c.name)}else{state.voiceParticipants[c.id]=[...arr,1];toast('🔊 Bạn đã tham gia '+c.name)}save();renderMembers();openVoicePanel(c)};$('#muteVoice').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent.includes('Tắt')?'🔊 Bật mic':'🎤 Tắt mic'};$('#deafenVoice').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent.includes('Điếc')?'🔇 Bỏ điếc':'🎧 Điếc'};}
function openAction(html){$('#actionContent').innerHTML=html;openModal('#actionModal')};function closeAction(){$('#actionModal').classList.remove('open')}
function globalSearchModal(){openAction('<h2>🔍 Tìm kiếm cộng đồng</h2><form class="form-grid" id="searchForm"><input id="globalSearchInput" placeholder="Tìm tin nhắn, thành viên, kênh..."><button>Tìm kiếm</button></form><div id="searchResults" class="search-results"></div>');$('#searchForm').onsubmit=e=>{e.preventDefault();const q=$('#globalSearchInput').value.trim().toLowerCase();const results=[];Object.entries(state.messages).forEach(([cid,arr])=>arr.forEach(m=>{if((m.text||'').toLowerCase().includes(q))results.push({m,c:state.servers.flatMap(s=>s.channels).find(c=>c.id===cid)} )}));state.members.forEach(m=>{if(m.name.toLowerCase().includes(q))results.push({member:m})});$('#searchResults').innerHTML=results.length?results.map(r=>r.member?'<div class="search-result"><b>'+escape(r.member.avatar)+' '+escape(r.member.name)+'</b><p>'+escape(r.member.bio||'')+'</p><small>Thành viên · '+escape(r.member.role)+'</small></div>':'<div class="search-result" data-jump="'+r.c.id+'"><b>#'+escape(r.c.name)+'</b><p>'+escape(r.m.text||'')+'</p><small>'+escape(member(r.m.member).name)+' · '+escape(r.m.time||'')+'</small></div>').join(''):'<div class="empty-state">Không tìm thấy kết quả.</div>';$$('[data-jump]').forEach(x=>x.onclick=()=>{const c=x.dataset.jump;for(const s of state.servers){if(s.channels.some(k=>k.id===c)){state.selectedServer=s.id;state.selectedChannel=c;break}}save();closeAction();renderAll()})}}
function schoolHubModal(){openAction('<h2>🏫 Trung tâm trường</h2><div class="announcement-card"><b>📢 Thông báo chính thức</b><small>Lịch học, học vụ, sự kiện và các thông tin quan trọng.</small></div><div class="announcement-card"><b>🎓 Tân sinh viên</b><small>Hướng dẫn, giải đáp và kết nối sinh viên mới.</small></div><div class="announcement-card"><b>📅 Sự kiện</b><small>Workshop, seminar, hoạt động ngoại khóa và CLB.</small></div><button id="goAnnouncement" class="primary-btn" style="width:100%">Mở kênh thông báo</button>');$('#goAnnouncement').onclick=()=>{state.selectedServer='onb';state.selectedChannel='announcements';save();closeAction();renderAll()}}
function friendsModal(){openAction('<h2>👥 Bạn bè</h2><div class="friend-row"><div class="member-avatar">👩🏻‍💻</div><div><b>Minh Anh</b><small>Online · Moderator</small></div><button>Nhắn tin</button></div><div class="friend-row"><div class="member-avatar">🎨</div><div><b>An Designer</b><small>Online · Thiết kế đồ họa</small></div><button>Nhắn tin</button></div><div class="friend-row"><div class="member-avatar">🧑🏻‍💻</div><div><b>Ngọc Duy Long</b><small>Online · CNTT</small></div><button>Nhắn tin</button></div><p class="muted">Bản local demo có thể mở rộng thành hệ thống bạn bè/DM realtime khi kết nối backend.</p>')}
function settingsModal(){openAction('<h2>⚙ Cài đặt cá nhân</h2><form class="form-grid" id="settingsForm"><label>Tên hiển thị<input id="settingsName" value="'+escape(state.user.name)+'"></label><label>Bio<textarea id="settingsBio" rows="3">'+escape(state.user.bio||'')+'</textarea></label><label>Kỹ năng, cách nhau bằng dấu phẩy<input id="settingsSkills" value="'+escape((state.user.skills||[]).join(', '))+'"></label><button>Lưu hồ sơ</button></form><button id="resetDemo" class="primary-btn" style="width:100%;margin-top:8px;background:#ed4245">Reset dữ liệu demo</button>');$('#settingsForm').onsubmit=e=>{e.preventDefault();state.user.name=$('#settingsName').value.trim()||'Gia Huy';state.user.bio=$('#settingsBio').value.trim();state.user.skills=$('#settingsSkills').value.split(',').map(x=>x.trim()).filter(Boolean);save();closeAction();renderAll();toast('✅ Đã cập nhật hồ sơ.')};$('#resetDemo').onclick=()=>{if(confirm('Reset toàn bộ dữ liệu cộng đồng trên trình duyệt này?')){localStorage.removeItem(KEY);location.reload()}}}
function editProfileModal(){settingsModal()}
function buildEmojiPicker(){$('#emojiGrid').innerHTML=EMOJIS.map(x=>'<button data-emoji-pick="'+x+'">'+x+'</button>').join('')}
function positionEmoji(){const b=$('#emojiBtn'),p=$('#emojiPop');if(!b||!p)return;const r=b.getBoundingClientRect();p.style.left=Math.max(8,r.right-300)+'px';p.style.top=Math.max(65,r.top-250)+'px'}
function showNotifications(){state.notifications=0;save();updateNotification();openAction('<h2>🔔 Thông báo</h2><div class="announcement-card"><b>🎉 Cộng đồng Oxford Nhà Bè</b><small>Bạn đã nhận điểm ONB từ hoạt động cộng đồng.</small></div><div class="announcement-card"><b>📢 Nhà trường</b><small>Có thông báo mới trong #thông-báo-nhà-trường.</small></div><div class="announcement-card"><b>👥 CLB</b><small>Các câu lạc bộ đang mở đăng ký thành viên.</small></div>')}
window.addEventListener('keydown',e=>{if(e.key==='Escape'){replyTo=null;$('#messageInput').placeholder='Nhắn #'+channel().name;$('#emojiPop').classList.remove('open')}});
init();
})();
